#version: '3.8'

services:
  app:
    build: ./nodejs_srv
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      - NODE_ENV=production
      - CONFIG_FILE=config.json 

    volumes:
      - ./node_srv:/app

  nodered:
    image: nodered/node-red:latest
    ports:
      - "1880:1880"
    volumes:
      - ./node_red_srv/flows.json:/data/flows.json
    command: /bin/sh -c "chmod -R 777 /data && npm start -- --userDir /data" 

  mysql:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: iot_data
    volumes:  
      - mysql_data:/var/lib/mysql
          
volumes:
  mysql_data:









#services:
#  postgres_db:
#    image: postgres:latest
#    restart: always
#    environment:
#      POSTGRES_DB: iot_data
#      POSTGRES_USER: harbaoui
#      POSTGRES_PASSWORD: "12345678"
#    volumes:
#      - ./db-data:/var/lib/postgresql/data
#    ports:
#      - "9999:9999"
#  #node_red:

#  nodejs_srv:
#    restart: always
#    build: ./nodejs_srv
#    ports:
#      - '3000:3000'
#    volumes:
#      - ./nodejs_srv/node_modules:/app/node_modules



