# Use the official Node-RED base image
FROM nodered/node-red:latest

# Set the working directory to /node_red_srv
WORKDIR /node_red_srv

COPY package.json ./

# Install dependencies
RUN npm install


# Copy the rest of the application code
COPY . .

# Expose the port used by Node-RED
EXPOSE 1880
